title: Simple Anki
name: Simple Anki
theme: jekyll-theme-cayman
show_downloads: true

github:
  owner_name: Astemir Boziev
  repository_name: Simple Anki
  zip_url: https://apps.apple.com/ru/app/simple-anki/id1562385336
